import type { Config } from 'tailwindcss'

export default {
    darkMode: 'class',
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
        "./components/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            fontFamily: {
                sans: ['Inter', 'sans-serif'],
                headline: ['Newsreader', 'serif'],
                body: ['Manrope', 'sans-serif'],
                label: ['Space Grotesk', 'monospace'],
            },
            colors: {
                'surface-tint': '#c6c6c7',
                'primary-fixed-dim': '#454747',
                'inverse-on-surface': '#303030',
                'tertiary-fixed': '#c00502',
                'inverse-primary': '#5d5f5f',
                'tertiary-fixed-dim': '#930000',
                'error-container': '#93000a',
                'surface-dim': '#131313',
                'outline-variant': '#474747',
                'secondary-fixed': '#c8c6c5',
                'on-tertiary': '#410000',
                'tertiary': '#ffdad4',
                'on-tertiary-fixed': '#ffffff',
                'tertiary-container': '#ff5541',
                'surface-container-highest': '#353535',
                'surface-variant': '#353535',
                'secondary-fixed-dim': '#adabaa',
                'on-tertiary-container': '#000000',
                'on-secondary-container': '#e5e2e1',
                'on-tertiary-fixed-variant': '#ffdad4',
                'on-primary': '#1a1c1c',
                'on-primary-fixed': '#ffffff',
                'on-background': '#e2e2e2',
                'surface-container-low': '#1b1b1b',
                'on-primary-fixed-variant': '#e2e2e2',
                'outline': '#919191',
                'primary-fixed': '#5d5f5f',
                'surface-container': '#1f1f1f',
                'on-surface-variant': '#c6c6c6',
                'inverse-surface': '#e2e2e2',
                'surface': '#131313',
                'surface-container-high': '#2a2a2a',
                'primary-container': '#d4d4d4',
                'secondary-container': '#474746',
                'on-surface': '#e2e2e2',
                'on-secondary': '#1c1b1b',
                'on-primary-container': '#000000',
                'on-error': '#690005',
                'on-error-container': '#ffdad6',
                'error': '#ffb4ab',
                'on-secondary-fixed': '#1c1b1b',
                'on-secondary-fixed-variant': '#3c3b3b',
                'surface-bright': '#393939',
                'surface-container-lowest': '#0e0e0e',
                border: "var(--border)",
                input: "var(--input)",
                ring: "var(--ring)",
                background: "var(--background)",
                foreground: "var(--foreground)",
                primary: {
                    DEFAULT: "var(--primary)",
                    foreground: "var(--primary-foreground)",
                },
                secondary: {
                    DEFAULT: "var(--secondary)",
                    foreground: "var(--secondary-foreground)",
                },
                destructive: {
                    DEFAULT: "var(--destructive)",
                    foreground: "var(--destructive-foreground)",
                },
                muted: {
                    DEFAULT: "var(--muted)",
                    foreground: "var(--muted-foreground)",
                },
                accent: {
                    DEFAULT: "var(--accent)",
                    foreground: "var(--accent-foreground)",
                },
                popover: {
                    DEFAULT: "var(--popover)",
                    foreground: "var(--popover-foreground)",
                },
                card: {
                    DEFAULT: "var(--card)",
                    foreground: "var(--card-foreground)",
                },
                // UseGlass — glassmorphism color tokens
                'glass': 'rgba(255, 255, 255, 0.55)',
                'glass-subtle': 'rgba(255, 255, 255, 0.40)',
                'glass-strong': 'rgba(255, 255, 255, 0.72)',
                'glass-panel': 'rgba(255, 255, 255, 0.65)',
                'glass-border': 'rgba(255, 255, 255, 0.70)',
                'glass-border-soft': 'rgba(228, 228, 231, 0.60)',
            },
            backdropBlur: {
                'glass': '16px',
                'glass-sm': '8px',
                'glass-lg': '24px',
            },
            boxShadow: {
                'glass': '0 1px 0 0 rgba(255,255,255,0.70) inset, 0 8px 32px -8px rgba(15,23,42,0.10), 0 2px 8px -2px rgba(15,23,42,0.06)',
                'glass-strong': '0 1px 0 0 rgba(255,255,255,0.85) inset, 0 24px 64px -12px rgba(15,23,42,0.18), 0 8px 24px -6px rgba(15,23,42,0.10)',
                'glass-hover': '0 1px 0 0 rgba(255,255,255,0.85) inset, 0 12px 36px -8px rgba(15,23,42,0.14), 0 4px 12px -2px rgba(15,23,42,0.08)',
            },
            borderRadius: {
                DEFAULT: '0rem',
                lg: '0rem',
                xl: '0rem',
                full: '9999px',
            },
        },
    },
    plugins: [
        require('@tailwindcss/typography'),
    ],
} satisfies Config